from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from time import sleep
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select

def load_mi(url):
    driver=webdriver.Chrome(service=Service('C:\Windows\chromedriver.exe'))
    driver.maximize_window()
    driver.get(url)
    return driver

def test_registracije_mi():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[1]/div/div/div[2]/a/span[2]").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/form/footer/div[3]/button").click()
    sleep(1)
    driver.find_element(By.NAME,'first_name').send_keys('sasa')
    driver.find_element(By.NAME,'last_name').send_keys('ristic')
    driver.find_element(By.NAME, 'email').send_keys('rsasa84@yahoo.com')
    driver.find_element(By.NAME, 'password').send_keys('sdebo84!')
    driver.find_element(By.NAME, 'password_confirmation').send_keys('sdebo84!')
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/div/div[2]/div/form/section/div[5]/label/span[1]").click()
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/div/div[2]/div/form/footer/button").click()
    sleep(3)
    element = driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/div/div[2]/div/form")
    element.screenshot('mi/Kreiranje_naloga.png')
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/div/div[2]/div/form/header/button").click()
    sleep(3)
    driver.quit()

def test_logovanja_mi():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[1]/div/div/div[2]/a").click()
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[1]/div/input").send_keys('rsasa84@yahoo.com')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[2]/div/input").send_keys('sdebo84!')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/footer/div[1]/button").click()
    sleep(2)
    element = driver.find_element(By.XPATH, "/html/body/div[1]/section")
    element.screenshot('mi/Logovanje.png')


def test_odjava():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div/div/div[2]/a").click()
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[1]/div/input").send_keys('rsasa84@yahoo.com')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[2]/div/input").send_keys('sdebo84!')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/footer/div[1]/button").click()
    sleep(2)
    element = driver.find_element(By.XPATH, "/html/body/div[1]/section")
    element.screenshot('mi/Logovanje.png')
    driver.find_element(By.XPATH,"//span[contains(text(),'Moj nalog')]").click()
    sleep(3)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[1]/div/div/div[2]/div[1]/div[2]/div/a[4]").click()
    sleep(2)
    driver.quit()

def test_sa_razlicitom_lozinkom():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div/div/div[2]/a").click()
    sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[1]/div/input").send_keys('rsasa84@yahoo.com')
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/div/form/section/div[2]/div/input").send_keys('rsasa84@yahoo.com')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/div/form/footer/div[1]/button").click()
    sleep(2)
    driver.save_screenshot('mi/Pogresan_log.png')
    driver.find_element(By.XPATH, "/html/body/div[3]/div[2]/button").click()
    sleep(3)
    driver.quit()

def test_uporedjivanja_uredjaja():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[1]/a").click()
    element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div/div[2]/div[1]/div")
    driver.execute_script("arguments[0].scrollIntoView();", element)
    sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[2]/div/div[2]/div[4]/i").click()
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[4]/div/div[2]/div[4]/i").click()
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div[2]/div/button[1]").click()
    sleep(2)
    rolo=driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[1]/h1")
    driver.execute_script("arguments[0].scrollIntoView();",rolo)
    sleep(1)
    driver.quit()

def test_promena_cena():
    driver=load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[1]/a").click()
    element = driver.find_element(By.XPATH, "//div[@class='column is-one-quarter is-hidden-mobile wkl-filters']")
    driver.execute_script("arguments[0].scrollIntoView();", element)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[2]/div/div[2]/div[1]/div[1]").click()
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/div/div[1]/input[2]").send_keys('30000')
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/div/div/button").click()
    sleep(1)
    element = driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div/div[2]/div[1]/div")
    driver.execute_script("arguments[0].scrollIntoView();", element)
    sleep(2)
    driver.quit()

def test_funkciju_korpe():
    driver=load_mi('https://mi-srbija.rs/')
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[1]").click()
    sleep(2)
    rol = driver.find_element(By.XPATH, "/html/body/div[1]/section/section")
    driver.execute_script("arguments[0].scrollIntoView();", rol)
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[6]/div/div[1]/a").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[2]/div[1]/div[2]/button").click()
    sleep(1)
    driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[1]/div/div/div[2]/div/div/div[2]/div/div[3]/div/div").click()

    element=driver.find_element(By.XPATH,"/html/body/div[1]/section/div/div/div/div/div[2]/section/div[1]/div/div/div[2]/div[1]/div[2]")
    element.screenshot('mi/Ukupna cena.png')
    sleep(2)

    mobilni=driver.find_element(By.XPATH, "/html/body/div[1]/section/div/div/div/div/div[2]/section/div[1]/div/div/div[1]/div/div[2]/div[1]/div/div[4]/div/select")
    dropdown=Select(mobilni)
    dropdown.select_by_value('0')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div/div/div/div/div[2]/section/div[1]/div/div/div[1]/div/a").click()
    driver.quit()

def test_kolicina_uredjaja():
    driver=load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[4]/a").click()
    sleep(2)

    proizvod=driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[11]/div/div[1]/a/img")
    driver.execute_script("arguments[0].scrollIntoView();", proizvod)
    sleep(2)

    actions = ActionChains(driver)
    actions.move_to_element(proizvod).perform()
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[11]/div/div[2]/div[5]/div/button").click()
    sleep(3)

    dugme=driver.find_element(By.XPATH, "//button[contains(text(), 'Pregled korpe i plaćanje')]")
    driver.execute_script("arguments[0].click();", dugme)

    driver.find_element(By.XPATH, "//span[contains(text(),'Korpa')]").click()
    sleep(3)
    driver.find_element(By.XPATH,"//html/body/div[1]/section/div/div/div/div/div[2]/section/div[1]/div/div/div[1]/div/div[2]/div/div/div[4]/div/select").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div/div/div/div/div[2]/section/div[1]/div/div/div[1]/div/div[2]/div/div/div[4]/div/select/option[1]").click()
    sleep(2)
    driver.get('https://mi-srbija.rs')
    sleep(2)
    driver.quit()

def test_dostupnost_uredjaja_u_radnjama():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[2]/a").click()
    sleep(1)
    element=driver.find_element(By.XPATH,"/html/body/div[1]/section/header/div/div/img")
    driver.execute_script("arguments[0].scrollIntoView();", element)
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div[1]/div[2]/div[3]/div/div/div[2]/div").click()
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[1]/div[8]/div[2]/div/button").click()
    sleep(2)
    element=driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[1]/div[8]/div[2]/div/div/div[2]/div/div")
    element.screenshot('mi/Radnje.png')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[1]/div[8]/div[2]/div/div/div[2]/button").click()
    sleep(2)
    driver.quit()

def test_hover_meni ():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)

    kancelarija=driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[3]/a")
    actions=ActionChains(driver)
    actions.move_to_element(kancelarija).perform()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[3]/div/div/div/div[4]/div/div[3]/div[3]/a").click()
    sleep(1)
    mis=driver.find_element(By.XPATH, "/html/body/div[1]/section/section[1]/div[2]/div/div[1]/div[7]/div/div/div[2]/div[2]")
    driver.execute_script("arguments[0].click();",mis)
    sleep(1)
    dugme=driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[2]/div[1]/div[1]/div/button[2]/i")
    for _ in range(3):
        dugme.click()
        sleep(1)
    dugme=driver.find_element(By.XPATH,"/html/body/div[1]/section/section[1]/div[2]/div/div[2]/div[1]/div[1]/div/button[1]/i")
    for _ in range(2):
        dugme.click()
        sleep(1)
    driver.quit()

def test_info_prodavnice():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    # driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/a").click()
    # sleep(1)
    element=driver.find_element(By.XPATH,"/html/body/div[1]/footer/div[2]")
    driver.execute_script("arguments[0].scrollIntoView();",element)
    sleep(2)
    info=driver.find_element(By.XPATH,"/html/body/div[1]/footer/div[2]/div/div")
    info.screenshot('mi/Info.png')
    driver.find_element(By.XPATH,"//a[contains(text(),'Xiaomi Store Delta City')]").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/footer/div[2]/div/div/div/div[3]/div/div[7]/div[1]/div[1]/div[2]/a").click()
    sleep(2)

    mi=driver.current_window_handle
    driver.find_element(By.XPATH, '/html/body/div[1]/footer/div[2]/div').click()
    sleep(2)
    driver.switch_to.window(driver.window_handles[-1])
    sleep(1)
    driver.switch_to.window(mi)
    sleep(1)

    assert  driver.current_url  ==  'https://mi-srbija.rs/'
    sleep(2)
    print('Otvorila se stranica google map')
    sleep(2)
    driver.quit()

def test_funkcije_copy():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[4]/a").click()
    tv=driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[11]")
    driver.execute_script("arguments[0].scrollIntoView();",tv)
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div/div[2]/div[3]/div/div[1]/div[11]/div/div[1]/a/img").click()
    sleep(1)
    tv=driver.find_element(By.XPATH,"/html/body/div[1]/section/div/section[1]/div/details/summary")
    driver.execute_script("arguments[0].scrollIntoView();", tv)
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div/section[1]/div/details").click()
    sleep(2)
    element = driver.find_element(By.XPATH,"/html/body/div[1]/section/div/section[1]/div/details/div/div/div/table/tbody/tr[12]")
    tekst = element.text
    print("Tekst sa stranice:", tekst)
    sleep(3)
    driver.quit()

def test_za_brisanje_uredjaja_za_uporedjivanje():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(2)
    driver.find_element(By.XPATH, "/html/body/div[1]/header/div/div[2]/div/div/div[3]/div[1]/a").click()
    driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div[1]/div[2]/div[3]/div/div[1]/div[1]/div/div[2]/div[4]/i").click()
    driver.find_element(By.XPATH, "/html/body/div[1]/section/section/div[1]/div[2]/div[3]/div/div[1]/div[3]/div/div[2]/div[4]/i").click()
    sleep(2)
    uporedjivanje=driver.find_element(By.XPATH,"/html/body/div[1]/section/section/div[2]")
    uporedjivanje.screenshot('mi/Uporedjivanje_uredjaja.png')
    driver.find_element(By.NAME,'clear_compare').click()
    sleep(2)
    uporedjivanje2 = driver.find_element(By.XPATH, "/html/body/div[3]/div[2]")
    uporedjivanje2.screenshot('mi/Brisanje_uporedjivanja_uredjaja.png')
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[3]/div[2]/footer/button[2]").click()
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/div/div/a").click()
    driver.quit()

def test_prodavnice_i_funkcije_u_njoj():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div[2]/div/div[3]/div/div[2]/div").click()
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div/div/div[2]/div/div/div[8]/h2/a").click()
    sleep(1)
    element = driver.find_element(By.XPATH, "/html/body/div[1]/section/div/div/div/div/div[2]/div/div/figure/img")
    driver.execute_script("arguments[0].scrollIntoView(true);", element)
    sleep(1)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div/div/div/div/div[3]/div/div[1]/div[1]/div[2]/a").click()
    sleep(5)
    mi = driver.current_window_handle
    driver.find_element(By.XPATH, '/html/body/div[1]/footer/div[2]/div').click()
    sleep(2)
    driver.switch_to.window(driver.window_handles[-1])
    sleep(1)
    driver.switch_to.window(mi)
    sleep(1)
    driver.quit()

def test_indikator_za_reklame():
    driver = load_mi('https://mi-srbija.rs/')
    sleep(1)
    pocetak=driver.find_element(By.XPATH,"/html/body/div[1]/section/div[1]/div/div/div[1]/div[1]/div/a/img")
    driver.execute_script("arguments[0].scrollIntoView();",pocetak)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div[1]/div/div/div[2]/a[1]/span").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div[1]/div/div/div[2]/a[3]/span").click()
    sleep(2)
    driver.find_element(By.XPATH,"/html/body/div[1]/section/div[1]/div/div/div[2]/a[5]").click()
    sleep(2)
    driver.quit()